---
title: "FSI_Subindicator"
author: "Silvia Li"
date: "2025-02-27"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Users/lixiaoya/Desktop/Mercy Corps Policy Lab/Data")
library(tidyverse)
library(readxl)
library(dplyr)
library(ggplot2)
library(stringr)

ocha <- read.csv("GHO 2025 Development Needs - Weighted averages.csv")
fsi_full<- read_excel("XL_FSI_fulldata.xlsx")
fsi_more <- read_excel("XL_FSI_data.xlsx")
```

```{r}
## making pin numeric
ocha <- ocha %>%
  mutate(new_pin = str_replace_all(people_in_need, ",", "")) %>%
  mutate(numeric_pin = as.numeric(new_pin))

## filtering to columns we need
ocha <- ocha[c("country", "calendar_year", "year_of_crisis",
                        "numeric_pin", "years_since_crisis")]

ocha <- ocha %>%
  mutate(country_year = paste0(country, calendar_year))
```
```{r}
## adding in UN population data
un_pop <- read_excel("/Users/lixiaoya/Desktop/Mercy Corps Policy Lab/Data/Total Population.xlsx")

```

```{r}
## concat year and country in ocha
ocha <- ocha %>%
  mutate(country_year = paste0(country, calendar_year))
```

```{r}
## concat year and country in UN pop
un_pop <- un_pop %>%
  mutate(country_year = paste0(Country, Time))

## making population as numeric
un_pop <- un_pop %>%
  mutate(total_country_population = as.numeric(Value))
```

```{r}
## merging columns to get population for each country in each year
merged_ocha_un <- merge(un_pop, ocha, by="country_year")
```

```{r}
## filtering so I only have columns I need
merged_ocha_un <- merged_ocha_un[c("country_year", "Country", 
                                   "total_country_population", "calendar_year", 
                                   "numeric_pin", "years_since_crisis", 
                                   "year_of_crisis")]

## Convert 'numeric_pin' to numeric if it's not
merged_ocha_un$numeric_pin <- as.numeric(as.character(merged_ocha_un$numeric_pin))

## Check and convert 'total_country_population' to numeric if necessary
merged_ocha_un$total_country_population <- as.numeric(as.character(merged_ocha_un$total_country_population))

## After ensuring both are numeric, perform the operation
merged_ocha_un <- merged_ocha_un %>%
  mutate(pin_proportion_of_country = numeric_pin / total_country_population)

```


```{r}
## Make dataframe from wide to long
fsi_panel <- fsi_full %>%
  pivot_longer(
    cols = -Country,  # Exclude the country column if it exists; otherwise, adjust accordingly
    names_to = "year_indicator",
    values_to = "value"
  ) %>%
  mutate(
    year = str_extract(year_indicator, "^[0-9]+"),  # Extract the year from the combined column
    indicator = str_remove(year_indicator, "^[0-9]+_")  # Remove the year part to leave just the indicator
  ) %>%
  select(-year_indicator) %>%  # Drop the combined column as it's no longer needed
  pivot_wider(
    names_from = indicator,
    values_from = value,
    names_prefix = ""  # Removes any prefix from the column names
  )

# View the panel dataframe
print(fsi_panel)
```

```{r}
fsi_panel <- fsi_panel %>%
  mutate(country_year = paste0(Country, year))
```

```{r}
#merge fsi and ocha data
complete_full_data <- merge(merged_ocha_un, fsi_panel, by="country_year")

#delete repeat column and rename the country column
complete_full_data <- complete_full_data %>%
  select(-c(Country.y))  

complete_full_data <- complete_full_data %>%
  rename(Country = Country.x)
```

```{r}
# Extract year and indicator, then adjust column names
fsi_more <- fsi_more %>%
  pivot_longer(
    cols = -Country,  # Exclude the Country column
    names_to = "year_indicator",
    values_to = "value"
  ) %>%
  mutate(
    year = str_extract(year_indicator, "^[0-9]+"),  # Extract the year from the combined column
    indicator = str_remove(year_indicator, "^[0-9]+_")  # Remove the year part to leave just the indicator
  ) %>%
  select(-year_indicator) %>%
  pivot_wider(
    names_from = indicator,
    values_from = value,
    names_prefix = ""  # Removes any prefix from the column names
  ) %>%
  rename(calendar_year = year)  # Rename 'year' to 'calendar_year'

# Concatenate country and calendar year to create a unique identifier
fsi_more <- fsi_more %>%
  mutate(country_year = paste0(Country, calendar_year))

# Ensure calendar_year is an integer
fsi_more <- fsi_more %>%
  mutate(calendar_year = as.integer(calendar_year))  # Convert calendar_year to integer

# Now try to bind the rows again
complete_full_data <- dplyr::bind_rows(complete_full_data, fsi_more)


```


```{r}
## making a new column for lag index scores - 0 year lag
complete_full_data <- complete_full_data %>%
  group_by(Country) %>%
  mutate(
    fsi_calendar_year_before_0_years = Total,
    security_apparatus_calendar_year_before_0_years = `C1: Security Apparatus`,
    factionalized_elites_calendar_year_before_0_years = `C2: Factionalized Elites`,
    group_grievance_calendar_year_before_0_years = `C3: Group Grievance`,
    economy_calendar_year_before_0_years = `E1: Economy`,
    economic_inequality_calendar_year_before_0_years = `E2: Economic Inequality`,
    humanflight__calendar_year_before_0_years = `E3: Human Flight and Brain Drain`,
    state_legitimacy_calendar_year_before_0_years = `P1: State Legitimacy`,
    public_services_calendar_year_before_0_years = `P2: Public Services`,
    humanrights_calendar_year_before_0_years = `P3: Human Rights`,
    demographic_pressures_calendar_year_before_0_years = `S1: Demographic Pressures`,
    refugees_and_IDPs_calendar_year_before_0_years = `S2: Refugees and IDPs`,
    external_intervention_calendar_year_before_0_years = `X1: External Intervention`,
  ) %>%
  ungroup()

```


```{r}
## making a new column for lag index scores - 1 year lag
complete_full_data <- complete_full_data %>%
  group_by(Country) %>%
  mutate(
    fsi_calendar_year_before_1_year = Total[match(calendar_year - 1, calendar_year)],
    security_apparatus_calendar_year_before_1_year = `C1: Security Apparatus`[match(calendar_year - 1, calendar_year)],
    factionalized_elites_calendar_year_before_1_year = `C2: Factionalized Elites`[match(calendar_year - 1, calendar_year)],
    group_grievance_calendar_year_before_1_year = `C3: Group Grievance`[match(calendar_year - 1, calendar_year)],
    economy_calendar_year_before_1_year = `E1: Economy`[match(calendar_year - 1, calendar_year)],
    economic_inequality_calendar_year_before_1_year = `E2: Economic Inequality`[match(calendar_year - 1, calendar_year)],
    humanflight_calendar_year_before_1_year = `E3: Human Flight and Brain Drain`[match(calendar_year - 1, calendar_year)],
    state_legitimacy_calendar_year_before_1_year = `P1: State Legitimacy`[match(calendar_year - 1, calendar_year)],
    public_services_calendar_year_before_1_year = `P2: Public Services`[match(calendar_year - 1, calendar_year)],
    humanrights_calendar_year_before_1_year = `P3: Human Rights`[match(calendar_year - 1, calendar_year)],
    demographic_pressures_calendar_year_before_1_year = `S1: Demographic Pressures`[match(calendar_year - 1, calendar_year)],
    refugees_and_IDPs_calendar_year_before_1_year = `S2: Refugees and IDPs`[match(calendar_year - 1, calendar_year)],
    external_intervention_calendar_year_before_1_year = `X1: External Intervention`[match(calendar_year - 1, calendar_year)]
  ) %>%
  ungroup()  # Remove the grouping for further operations

```


```{r}
## Do the same for 2 year lag
complete_full_data <- complete_full_data %>%
  group_by(Country) %>%
  mutate(
    fsi_calendar_year_before_2_years = Total[match(calendar_year - 2, calendar_year)],
    security_apparatus_calendar_year_before_2_years = `C1: Security Apparatus`[match(calendar_year - 2, calendar_year)],
    factionalized_elites_calendar_year_before_2_years = `C2: Factionalized Elites`[match(calendar_year - 2, calendar_year)],
    group_grievance_calendar_year_before_2_years = `C3: Group Grievance`[match(calendar_year - 2, calendar_year)],
    economy_calendar_year_before_2_years = `E1: Economy`[match(calendar_year - 2, calendar_year)],
    economic_inequality_calendar_year_before_2_years = `E2: Economic Inequality`[match(calendar_year - 2, calendar_year)],
    humanflight_calendar_year_before_2_years = `E3: Human Flight and Brain Drain`[match(calendar_year - 2, calendar_year)],
    state_legitimacy_calendar_year_before_2_years = `P1: State Legitimacy`[match(calendar_year - 2, calendar_year)],
    public_services_calendar_year_before_2_years = `P2: Public Services`[match(calendar_year - 2, calendar_year)],
    humanrights_calendar_year_before_2_years = `P3: Human Rights`[match(calendar_year - 2, calendar_year)],
    demographic_pressures_calendar_year_before_2_years = `S1: Demographic Pressures`[match(calendar_year - 2, calendar_year)],
    refugees_and_IDPs_calendar_year_before_2_years = `S2: Refugees and IDPs`[match(calendar_year - 2, calendar_year)],
    external_intervention_calendar_year_before_2_years = `X1: External Intervention`[match(calendar_year - 2, calendar_year)],
  ) %>%
  ungroup()  # Remove the grouping for further unrestricted operations on the data frame


```

```{r}
complete_full_data <- complete_full_data %>%
  group_by(Country) %>%
  mutate(
    fsi_calendar_year_before_3_years = Total[match(calendar_year - 3, calendar_year)],
    security_apparatus_calendar_year_before_3_years = `C1: Security Apparatus`[match(calendar_year - 3, calendar_year)],
    factionalized_elites_calendar_year_before_3_years = `C2: Factionalized Elites`[match(calendar_year - 3, calendar_year)],
    group_grievance_calendar_year_before_3_years = `C3: Group Grievance`[match(calendar_year - 3, calendar_year)],
    economy_calendar_year_before_3_years = `E1: Economy`[match(calendar_year - 3, calendar_year)],
    economic_inequality_calendar_year_before_3_years = `E2: Economic Inequality`[match(calendar_year - 3, calendar_year)],
    humanflight_calendar_year_before_3_years = `E3: Human Flight and Brain Drain`[match(calendar_year - 3, calendar_year)],
    state_legitimacy_calendar_year_before_3_years = `P1: State Legitimacy`[match(calendar_year - 3, calendar_year)],
    public_services_calendar_year_before_3_years = `P2: Public Services`[match(calendar_year - 3, calendar_year)],
    humanrights_calendar_year_before_3_years = `P3: Human Rights`[match(calendar_year - 3, calendar_year)],
    demographic_pressures_calendar_year_before_3_years = `S1: Demographic Pressures`[match(calendar_year - 3, calendar_year)],
    refugees_and_IDPs_calendar_year_before_3_years = `S2: Refugees and IDPs`[match(calendar_year - 3, calendar_year)],
    external_intervention_calendar_year_before_3_years = `X1: External Intervention`[match(calendar_year - 3, calendar_year)],
  ) %>%
  ungroup()  # Remove the grouping for further unrestricted operations on the data frame
    
```

```{r}
complete_full_data <- complete_full_data %>%
  group_by(Country) %>%
  mutate(
    fsi_calendar_year_before_5_years = Total[match(calendar_year - 5, calendar_year)],
    security_apparatus_calendar_year_before_5_years = `C1: Security Apparatus`[match(calendar_year - 5, calendar_year)],
    factionalized_elites_calendar_year_before_5_years = `C2: Factionalized Elites`[match(calendar_year - 5, calendar_year)],
    group_grievance_calendar_year_before_5_years = `C3: Group Grievance`[match(calendar_year - 5, calendar_year)],
    economy_calendar_year_before_5_years = `E1: Economy`[match(calendar_year - 5, calendar_year)],
    economic_inequality_calendar_year_before_5_years = `E2: Economic Inequality`[match(calendar_year - 5, calendar_year)],
    humanflight_calendar_year_before_5_years = `E3: Human Flight and Brain Drain`[match(calendar_year - 5, calendar_year)],
    state_legitimacy_calendar_year_before_5_years = `P1: State Legitimacy`[match(calendar_year - 5, calendar_year)],
    public_services_calendar_year_before_5_years = `P2: Public Services`[match(calendar_year - 5, calendar_year)],
    humanrights_calendar_year_before_5_years = `P3: Human Rights`[match(calendar_year - 5, calendar_year)],
    demographic_pressures_calendar_year_before_5_years = `S1: Demographic Pressures`[match(calendar_year - 5, calendar_year)],
    refugees_and_IDPs_calendar_year_before_5_years = `S2: Refugees and IDPs`[match(calendar_year - 5, calendar_year)],
    external_intervention_calendar_year_before_5_years = `X1: External Intervention`[match(calendar_year - 5, calendar_year)]
  ) %>%
  ungroup()  # Remove the grouping for further unrestricted operations on the data frame
    
```


```{r}

## making a initial year 0 dataframe
initial_crisis_year_data <- complete_full_data %>% filter(years_since_crisis == 0)

## Regression for 0 year lag for year of crisis
crisis_reg_lag_0 <- lm(pin_proportion_of_country ~ 
                   security_apparatus_calendar_year_before_0_years +
                   factionalized_elites_calendar_year_before_0_years +
                   group_grievance_calendar_year_before_0_years +
                   economy_calendar_year_before_0_years +
                   economic_inequality_calendar_year_before_0_years +
                   humanflight__calendar_year_before_0_years +
                   state_legitimacy_calendar_year_before_0_years +
                   public_services_calendar_year_before_0_years +
                   humanrights_calendar_year_before_0_years +
                   demographic_pressures_calendar_year_before_0_years +
                   refugees_and_IDPs_calendar_year_before_0_years +
                   external_intervention_calendar_year_before_0_years,
                 data = initial_crisis_year_data)
summary(crisis_reg_lag_0)
nobs(crisis_reg_lag_0)
```
```{r}
## Regression for 1 year lag for year of crisis
crisis_reg_lag_1 <- lm(pin_proportion_of_country ~ 
                   security_apparatus_calendar_year_before_1_year +
                   factionalized_elites_calendar_year_before_1_year +
                   group_grievance_calendar_year_before_1_year +
                   economy_calendar_year_before_1_year +
                   economic_inequality_calendar_year_before_1_year +
                   humanflight_calendar_year_before_1_year +
                   state_legitimacy_calendar_year_before_1_year +
                   public_services_calendar_year_before_1_year +
                   humanrights_calendar_year_before_1_year +
                   demographic_pressures_calendar_year_before_1_year +
                   refugees_and_IDPs_calendar_year_before_1_year +
                   external_intervention_calendar_year_before_1_year,
                 data = initial_crisis_year_data)
summary(crisis_reg_lag_1)
nobs(crisis_reg_lag_1)
```
```{r}
## Regression for 2 year lag for year of crisis
crisis_reg_lag_2 <- lm(pin_proportion_of_country ~ 
                   security_apparatus_calendar_year_before_2_years +
                   factionalized_elites_calendar_year_before_2_years +
                   group_grievance_calendar_year_before_2_years +
                   economy_calendar_year_before_2_years +
                   economic_inequality_calendar_year_before_2_years +
                   humanflight_calendar_year_before_2_years +
                   state_legitimacy_calendar_year_before_2_years +
                   public_services_calendar_year_before_2_years +
                   humanrights_calendar_year_before_2_years +
                   demographic_pressures_calendar_year_before_2_years +
                   refugees_and_IDPs_calendar_year_before_2_years +
                   external_intervention_calendar_year_before_2_years,
                 data = initial_crisis_year_data)
summary(crisis_reg_lag_2)
nobs(crisis_reg_lag_2)
```

```{r}
## Regression for 3 year lag for year of crisis
crisis_reg_lag_3 <- lm(pin_proportion_of_country ~ 
                   security_apparatus_calendar_year_before_3_years +
                   factionalized_elites_calendar_year_before_3_years +
                   group_grievance_calendar_year_before_3_years +
                   economy_calendar_year_before_3_years +
                   economic_inequality_calendar_year_before_3_years +
                   humanflight_calendar_year_before_3_years +
                   state_legitimacy_calendar_year_before_3_years +
                   public_services_calendar_year_before_3_years +
                   humanrights_calendar_year_before_3_years +
                   demographic_pressures_calendar_year_before_3_years +
                   refugees_and_IDPs_calendar_year_before_3_years +
                   external_intervention_calendar_year_before_3_years,
                 data = initial_crisis_year_data)
summary(crisis_reg_lag_3)
nobs(crisis_reg_lag_3)
```

```{r}
## Regression for 5 year lag for year of crisis
crisis_reg_lag_5 <- lm(pin_proportion_of_country ~
                   security_apparatus_calendar_year_before_5_years +
                   factionalized_elites_calendar_year_before_5_years +
                   group_grievance_calendar_year_before_5_years +
                   economy_calendar_year_before_5_years +
                   economic_inequality_calendar_year_before_5_years +
                   humanflight_calendar_year_before_5_years +
                   state_legitimacy_calendar_year_before_5_years +
                   public_services_calendar_year_before_5_years +
                   humanrights_calendar_year_before_5_years +
                   demographic_pressures_calendar_year_before_5_years +
                   refugees_and_IDPs_calendar_year_before_5_years +
                   external_intervention_calendar_year_before_5_years,
                 data = initial_crisis_year_data)
summary(crisis_reg_lag_5)
nobs(crisis_reg_lag_5)
```


```{r}
## Panel Regression for 0 year lag 
# Linear regression model using the newly created columns as predictors
panel_reg_lag_0 <- lm(pin_proportion_of_country ~ 
                   security_apparatus_calendar_year_before_0_years +
                   factionalized_elites_calendar_year_before_0_years +
                   group_grievance_calendar_year_before_0_years +
                   economy_calendar_year_before_0_years +
                   economic_inequality_calendar_year_before_0_years +
                   humanflight__calendar_year_before_0_years +
                   state_legitimacy_calendar_year_before_0_years +
                   public_services_calendar_year_before_0_years +
                   humanrights_calendar_year_before_0_years +
                   demographic_pressures_calendar_year_before_0_years +
                   refugees_and_IDPs_calendar_year_before_0_years +
                   external_intervention_calendar_year_before_0_years,
                 data = complete_full_data)
summary(panel_reg_lag_0)
nobs(panel_reg_lag_0)
```

```{r}
## Panel Regression for 1 year lag
panel_reg_lag_1 <- lm(pin_proportion_of_country ~ 
                   security_apparatus_calendar_year_before_1_year +
                   factionalized_elites_calendar_year_before_1_year +
                   group_grievance_calendar_year_before_1_year +
                   economy_calendar_year_before_1_year +
                   economic_inequality_calendar_year_before_1_year +
                   humanflight_calendar_year_before_1_year +
                   state_legitimacy_calendar_year_before_1_year +
                   public_services_calendar_year_before_1_year +
                   humanrights_calendar_year_before_1_year +
                   demographic_pressures_calendar_year_before_1_year +
                   refugees_and_IDPs_calendar_year_before_1_year +
                   external_intervention_calendar_year_before_1_year,
                 data = complete_full_data)
summary(panel_reg_lag_1)
nobs(panel_reg_lag_1)
```

```{r}
## Panel Regression for 2 year lag
panel_reg_lag_2 <- lm(pin_proportion_of_country ~ 
                   security_apparatus_calendar_year_before_2_years +
                   factionalized_elites_calendar_year_before_2_years +
                   group_grievance_calendar_year_before_2_years +
                   economy_calendar_year_before_2_years +
                   economic_inequality_calendar_year_before_2_years +
                   humanflight_calendar_year_before_2_years +
                   state_legitimacy_calendar_year_before_2_years +
                   public_services_calendar_year_before_2_years +
                   humanrights_calendar_year_before_2_years +
                   demographic_pressures_calendar_year_before_2_years +
                   refugees_and_IDPs_calendar_year_before_2_years +
                   external_intervention_calendar_year_before_2_years,
                 data = complete_full_data)
summary(panel_reg_lag_2)
nobs(panel_reg_lag_2)
```

```{r}
## Panel Regression for 3 year lag
panel_reg_lag_3 <- lm(pin_proportion_of_country ~ 
                   security_apparatus_calendar_year_before_3_years +
                   factionalized_elites_calendar_year_before_3_years +
                   group_grievance_calendar_year_before_3_years +
                   economy_calendar_year_before_3_years +
                   economic_inequality_calendar_year_before_3_years +
                   humanflight_calendar_year_before_3_years +
                   state_legitimacy_calendar_year_before_3_years +
                   public_services_calendar_year_before_3_years +
                   humanrights_calendar_year_before_3_years +
                   demographic_pressures_calendar_year_before_3_years +
                   refugees_and_IDPs_calendar_year_before_3_years +
                   external_intervention_calendar_year_before_3_years,
                 data = complete_full_data)
summary(panel_reg_lag_3)
nobs(panel_reg_lag_3)
```

```{r}
## Panel Regression for 5 year lag
panel_reg_lag_5 <- lm(pin_proportion_of_country ~
                   security_apparatus_calendar_year_before_5_years +
                   factionalized_elites_calendar_year_before_5_years +
                   group_grievance_calendar_year_before_5_years +
                   economy_calendar_year_before_5_years +
                   economic_inequality_calendar_year_before_5_years +
                   humanflight_calendar_year_before_5_years +
                   state_legitimacy_calendar_year_before_5_years +
                   public_services_calendar_year_before_5_years +
                   humanrights_calendar_year_before_5_years +
                   demographic_pressures_calendar_year_before_5_years +
                   refugees_and_IDPs_calendar_year_before_5_years +
                   external_intervention_calendar_year_before_5_years,
                 data = complete_full_data)
summary(panel_reg_lag_5)
nobs(panel_reg_lag_5)
```
```{r}
# fixed effect panel regression for lag year = 0
fe_model_0_lag <- feols(pin_proportion_of_country ~
                   security_apparatus_calendar_year_before_0_years +
                   factionalized_elites_calendar_year_before_0_years +
                   group_grievance_calendar_year_before_0_years +
                   economy_calendar_year_before_0_years +
                   economic_inequality_calendar_year_before_0_years +
                   humanflight__calendar_year_before_0_years +
                   state_legitimacy_calendar_year_before_0_years +
                   public_services_calendar_year_before_0_years +
                   humanrights_calendar_year_before_0_years +
                   demographic_pressures_calendar_year_before_0_years +
                   refugees_and_IDPs_calendar_year_before_0_years +
                   external_intervention_calendar_year_before_0_years
                   | Country  + calendar_year, data = complete_full_data)
summary (fe_model_0_lag)
nobs(fe_model_0_lag)
```
```{r}
# fixed effect panel regression for lag year = 1
fe_model_1_lag <- feols(pin_proportion_of_country ~
                   security_apparatus_calendar_year_before_1_year +
                   factionalized_elites_calendar_year_before_1_year +
                   group_grievance_calendar_year_before_1_year +
                   economy_calendar_year_before_1_year +
                   economic_inequality_calendar_year_before_1_year +
                   humanflight_calendar_year_before_1_year +
                   state_legitimacy_calendar_year_before_1_year +
                   public_services_calendar_year_before_1_year +
                   humanrights_calendar_year_before_1_year +
                   demographic_pressures_calendar_year_before_1_year +
                   refugees_and_IDPs_calendar_year_before_1_year +
                   external_intervention_calendar_year_before_1_year
                   | Country  + calendar_year, data = complete_full_data)
summary (fe_model_1_lag)
```
```{r}
# fixed effect panel regression for lag year = 2
fe_model_2_lag <- feols(pin_proportion_of_country ~
                   security_apparatus_calendar_year_before_2_years +
                   factionalized_elites_calendar_year_before_2_years +
                   group_grievance_calendar_year_before_2_years +
                   economy_calendar_year_before_2_years +
                   economic_inequality_calendar_year_before_2_years +
                   humanflight_calendar_year_before_2_years +
                   state_legitimacy_calendar_year_before_2_years +
                   public_services_calendar_year_before_2_years +
                   humanrights_calendar_year_before_2_years +
                   demographic_pressures_calendar_year_before_2_years +
                   refugees_and_IDPs_calendar_year_before_2_years +
                   external_intervention_calendar_year_before_2_years
                   | Country  + calendar_year, data = complete_full_data)
summary (fe_model_2_lag)
```
```{r}
# fixed effect panel regression for lag year = 3
fe_model_3_lag <- feols(pin_proportion_of_country ~
                   security_apparatus_calendar_year_before_3_years +
                   factionalized_elites_calendar_year_before_3_years +
                   group_grievance_calendar_year_before_3_years +
                   economy_calendar_year_before_3_years +
                   economic_inequality_calendar_year_before_3_years +
                   humanflight_calendar_year_before_3_years +
                   state_legitimacy_calendar_year_before_3_years +
                   public_services_calendar_year_before_3_years +
                   humanrights_calendar_year_before_3_years +
                   demographic_pressures_calendar_year_before_3_years +
                   refugees_and_IDPs_calendar_year_before_3_years +
                   external_intervention_calendar_year_before_3_years
                   | Country  + calendar_year, data = complete_full_data)
summary (fe_model_3_lag)
```


```{r}
# fixed effect panel regression for lag year = 5
fe_model_5_lag <- feols(pin_proportion_of_country ~
                   security_apparatus_calendar_year_before_5_years +
                   factionalized_elites_calendar_year_before_5_years +
                   group_grievance_calendar_year_before_5_years +
                   economy_calendar_year_before_5_years +
                   economic_inequality_calendar_year_before_5_years +
                   humanflight_calendar_year_before_5_years +
                   state_legitimacy_calendar_year_before_5_years +
                   public_services_calendar_year_before_5_years +
                   humanrights_calendar_year_before_5_years +
                   demographic_pressures_calendar_year_before_5_years +
                   refugees_and_IDPs_calendar_year_before_5_years +
                   external_intervention_calendar_year_before_5_years
                   | Country  + calendar_year, data = complete_full_data)
summary (fe_model_5_lag)
```

